server_host = "127.0.0.1"
server_port = 7777

[[client]]
name = "test"
local_ip = "127.0.0.1"
local_port = 5000
remote_port = 21001
secret_key = "123456"

[[client]]
name = "test1"
local_ip = "127.0.0.1"
local_port = 6000
remote_port = 21002
secret_key = "123456"